[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.11"

[dependencies]
risc0-zkvm-guest = "0.11"
image = { version = "0.24.5", features = ["webp", "png"], default-features = false }
