[package]
name = "waldo-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "1.0.0-rc.2"

[dependencies]
image = { version = "0.24.5", default-features = false }
merkle_light = "0.4"
once_cell = "1.17"
risc0-zkvm = { version = "1.0.0-rc.2", default-features = false, features = ["std", "metal"] }
serde = "1.0"
waldo-core = { path = "../../core" }

[profile.release]
lto = true
opt-level = 3

[patch.crates-io]
risc0-zkp = { path = "../../../../risc0/risc0/zkp" }
risc0-zkvm = { path = "../../../../risc0/risc0/zkvm" }
risc0-build = { path = "../../../../risc0/risc0/build" }
