[package]
name = "waldo-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.11"

[dependencies]
bytemuck = "1.12"
image = { version = "0.24.5", default-features = false }
merkle_light = "0.4"
risc0-zkvm = { version = "0.11", default-features = false }
risc0-zkvm-guest = "0.11"
serde = "1.0"
waldo-core = { path = "../../core", features = ["zkvm-guest"] }
