[package]
name = "waldo-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "1.0.0-rc.2"

[dependencies]
bytemuck = "1.12"
divrem = "1.0.0"
image = { version = "0.24.5", default-features = false }
merkle_light = "0.4"
once_cell = "1.17"
risc0-zkvm = { version = "1.0.0-rc.2", default-features = false, features = ["std"] }
serde = "1.0"
waldo-core = { path = "../../core" }

[profile.release]
lto = true
opt-level = "z"

[patch.crates-io]
merkle_light = { path = "../../../../merkle_light/merkle" }
