[package]
name = "waldo-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12"
cfg-if = "1.0.0"
merkle_light = "0.4.0"
risc0-zkp = { version = "0.11", default-features = false }
risc0-zkvm = { version = "0.11", default-features = false, optional = true }
risc0-zkvm-guest = { version = "0.11", optional = true }
static_assertions = "1.1.0"
serde = "1.0"

[dev-dependencies]
bincode = "1.3.3"
hex = "0.4.3"
rand = "0.8.5"
sha2 = "0.10.6"

[features]
zkvm-guest = ["risc0-zkvm-guest", "risc0-zkvm"]
zkvm-host = ["risc0-zkvm"]
