[package]
name = "waldo-host"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
bytemuck = "1.12"
clap = { version = "4.0", features = ["derive"] }
image = "0.24.5"
rand = "0.8.5"
risc0-zkp = "1.0.0-rc.2"
risc0-zkvm = { version = "1.0.0-rc.2", default-features = false, features = ["std", "prove", "metal"] }
serde = "1.0"
viuer = "0.6"
waldo-core = { path = "../core" }
waldo-methods = { path = "../methods" }
